AllCops:
  DisabledByDefault: true

Style/MultilineTernaryOperator:
  Enabled: true

# Cop supports --auto-correct.
Style/DefWithParentheses:
  Enabled: true

# Cop supports --auto-correct.
Style/MethodCallWithoutArgsParentheses:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleInsidePipes, SupportedStyles.
Layout/SpaceAroundBlockParameters:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline, SupportedStyles.
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline, SupportedStyles.
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

# Cop supports --auto-correct.
Layout/SpaceBeforeFirstArg:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Layout/FirstParameterIndentation:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: AllowSafeAssignment.
Style/ParenthesesAroundCondition:
  Enabled: true

# Cop supports --auto-correct.
Style/SpecialGlobalVars:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
Style/SymbolProc:
  Enabled: true

# Cop supports --auto-correct.
Style/Lambda:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MethodDefParentheses:
  Enabled: true

# Cop supports --auto-correct.
Style/EmptyLiteral:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, UseHashRocketsWithSymbolValues.
Style/HashSyntax:
  Enabled: true

# Cop supports --auto-correct.
Style/Not:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Enabled: true

# Cop supports --auto-correct.
Layout/SpaceAfterComma:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SignalException:
  Enabled: true

# Cop supports --auto-correct.
Style/LineEndConcatenation:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AndOr:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, AutoCorrectEncodingComment.
Style/Encoding:
  Enabled: true

# Cop supports --auto-correct.
Lint/UnusedMethodArgument:
  Enabled: true

# Cop supports --auto-correct.
Layout/ArrayAlignment:
  Enabled: true

# Cop supports --auto-correct.
Style/ColonMethodCall:
  Enabled: true

# Cop supports --auto-correct.
Lint/UnusedBlockArgument:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Layout/DotPosition:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyElse:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: MultiSpaceAllowedForOperators.
Layout/SpaceAroundOperators:
  Enabled: true

# Cop supports --auto-correct.
Layout/SpaceBeforeComma:
  Enabled: true

# Cop supports --auto-correct.
Layout/SpaceInsideParens:
  Enabled: true

# Cop supports --auto-correct.
Style/PreferredHashMethods:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ProceduralMethods, FunctionalMethods, IgnoredMethods.
Style/BlockDelimiters:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassCheck:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Layout/ParameterAlignment:
  Enabled: true

Layout/ConditionPosition:
  Enabled: true
